### ISSUE TITLE
我把一个类的对象序列化成byte[] ，传送时，发生了错误

### ISSUE THREAD

**Issue by yogioh123456** [skywind3000/kcp#181]
System.ArgumentException: Source array was not long enough. Check the source index, length, and the array's lower bounds.
Parameter name: sourceArray
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
   at SGF.Network.KCP.KCP.Send(Byte[] buffer, Int32 bufferSize) in E:\gitvs\KcpServer\KcpServer\KcpServer\Network\KCP\kcp.cs:line 353

**Comment by yogioh123456** [comment]
我是这样序列化的
`        /// <summary>
        /// 将对象转换为byte数组
        /// </summary>
        /// <param name="obj">被转换对象</param>
        /// <returns>转换后byte数组</returns>
        public static byte[] Object2Bytes(this object obj)
        {
            byte[] buff;
            using (MemoryStream ms = new MemoryStream())
            {
                IFormatter iFormatter = new BinaryFormatter();
                iFormatter.Serialize(ms, obj);
                buff = ms.GetBuffer();
            }
            return buff;
        }`

**Comment by yogioh123456** [comment]
.net core环境下

**Comment by skywind3000** [comment]
你该去 kcp 的.net项目那里提bug啊
